apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # finalizer tells ArgoCD, "Before you delete this app, go and delete every single resource inside of it."
spec:
  project: default
  source:
    repoURL: https://github.com/AbstractLK/task-management-k8s-config-dev.git
    targetRevision: HEAD
    path: argocd-apps # Watches the folder containing your two app YAMLs
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true