apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: {{.Values.images.authService}}
        ports:
        - containerPort: 4001
        env:
        - name: PORT
          value: "4001"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: task-management-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: task-management-secrets
              key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service # This is the internal DNS name Nginx will look for
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001