# This is the "pointer" file that goes into Git. It tells ESO which parameters to fetch from AWS and what to name the resulting Kubernetes Secret.

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: task-management-external-secret
spec:
  refreshInterval: "1h" # ESO will check AWS for updates every hour
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: task-management-secrets # Must match the secretKeyRef in your deployments!
    creationPolicy: Owner
  data:
  - secretKey: MONGODB_URI
    remoteRef:
      key: /task-management/MONGODB_URI
  - secretKey: JWT_SECRET
    remoteRef:
      key: /task-management/JWT_SECRET