apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{.Values.images.frontend}}
        ports:
        - containerPort: 80 # Or 3000, depending on your container setup
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # type: LoadBalancer # This tells AWS to provision an external Load Balancer automatically
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # Or 3000