# A SecretStore tells ESO how to authenticate with AWS

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-ssm-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-southeast-1
      auth:
        jwt:
          ServiceAccountRef:
            name: eso-service-account