# ==========================================
# TASK SERVICE
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: {{.Values.images.taskService}}
        ports:
        - containerPort: 4002
        env:
        - name: PORT
          value: "4002"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: task-management-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: task-management-secrets
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002